name: zapatas
description: Zapatas

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^2.0.4
  cupertino_icons: ^1.0.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/menu.json
    - assets/
  fonts:
    - family: Burrito
      fonts:
        - asset: assets/burrito.TTF
    - family: Roboto
      fonts:
        - asset: assets/roboto.TTF
  uses-material-design: true



